
sudo: required

addons:
  chrome: stable

language: node_js
node_js:
  - "8.9"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install -g cordova@8.0.0 ionic@3.19.0
  - npm install
script:
  - npm run test:ci
#  - npm run release
